/**
 * @file    usbd_cdc_if.c
 * @brief   USB CDC ACM interface — bridge between USB stack and application.
 *
 * This file is a TEMPLATE. In a real STM32CubeMX project, the CubeMX code
 * generator will create a proper usbd_cdc_if.c. This template shows the
 * expected structure and callbacks.
 *
 * To build with actual USB support:
 *   1. Open firmware/STM32G474RET6.ioc in STM32CubeMX
 *   2. Enable USB_OTG_FS in Device mode
 *   3. Select Communication Device Class (CDC)
 *   4. Generate code
 *   5. Copy generated usbd_cdc_if.c to Core/Src/
 *
 * The SCO firmware calls CDC_Receive_Callback() when USB data arrives
 * and USB_Send() to transmit data back.
 */

#include "main.h"
#include "usbd_cdc.h"
#include <string.h>

/* ── USB CDC Structures (generated by CubeMX) ──────────────────────────── */

/* USB Device Core handle */
USBD_HandleTypeDef hUsbDeviceFS;

/* CDC Line Coding (default: 115200 8N1) */
USBD_CDC_LineCodingTypeDef LineCoding = {
    .bitrate    = 115200,
    .format     = 0x00,  /* 1 stop bit */
    .paritytype = 0x00,  /* None */
    .datatype   = 0x08,  /* 8 data bits */
};

/* CDC receive buffer */
#define APP_RX_DATA_SIZE  1024
static uint8_t UserRxBuffer[APP_RX_DATA_SIZE];

/* ── External callback declaration (defined in main.c) ─────────────────── */

extern void CDC_Receive_Callback(uint8_t *buf, uint32_t len);

/* ── CDC Init ──────────────────────────────────────────────────────────── */

/**
 * @brief  Initialize USB CDC device.
 *         Called from main.c MX_USB_CDC_Init().
 */
void MX_USB_DEVICE_Init(void)
{
    if (USBD_Init(&hUsbDeviceFS, &HS_FS_Desc, DEVICE_FS) != USBD_OK) {
        Error_Handler();
    }
    if (USBD_RegisterClass(&hUsbDeviceFS, &USBD_CDC) != USBD_OK) {
        Error_Handler();
    }
    if (USBD_CDC_RegisterInterface(&hUsbDeviceFS, &USBD_CDC_fops_FS) != USBD_OK) {
        Error_Handler();
    }
    if (USBD_Start(&hUsbDeviceFS) != USBD_OK) {
        Error_Handler();
    }

    /* Prepare receive */
    USBD_CDC_SetRxBuffer(&hUsbDeviceFS, UserRxBuffer);
    USBD_CDC_ReceivePacket(&hUsbDeviceFS);
}

/* ── CDC Callbacks (called by USB stack) ───────────────────────────────── */

/**
 * @brief  Called when USB CDC receives a data packet.
 */
static int8_t CDC_Receive_FS(uint8_t *Buf, uint32_t *Len)
{
    /* Forward to application */
    CDC_Receive_Callback(Buf, *Len);

    /* Re-arm reception */
    USBD_CDC_SetRxBuffer(&hUsbDeviceFS, UserRxBuffer);
    USBD_CDC_ReceivePacket(&hUsbDeviceFS);

    return USBD_OK;
}

/**
 * @brief  Called when USB CDC control requests arrive
 *         (e.g., line coding, control line state).
 */
static int8_t CDC_Control_FS(uint8_t cmd, uint8_t *pbuf, uint16_t length)
{
    switch (cmd) {
    case CDC_SEND_ENCAPSULATED_COMMAND:
        break;
    case CDC_GET_ENCAPSULATED_RESPONSE:
        break;
    case CDC_SET_LINE_CODING:
        memcpy(&LineCoding, pbuf, sizeof(LineCoding));
        break;
    case CDC_GET_LINE_CODING:
        memcpy(pbuf, &LineCoding, sizeof(LineCoding));
        break;
    case CDC_SET_CONTROL_LINE_STATE:
        break;
    default:
        break;
    }
    return USBD_OK;
}

/* ── CDC Interface Callbacks Structure ──────────────────────────────────── */

USBD_CDC_ItfTypeDef USBD_CDC_fops_FS = {
    .Init       = NULL,
    .DeInit     = NULL,
    .Control    = CDC_Control_FS,
    .Receive    = CDC_Receive_FS,
};
